sudo: required
services:
    - docker

before_install:
    - docker build -t lsengar/react-dev-travis -f Dockerfile.dev .

scripts:
    - docker run lsengar/react-dev-travis npm run test -- --coverage
